# Generated by Django 4.0 on 2023-02-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handlinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handling', models.TextField()),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionsNavn', models.CharField(max_length=255)),
                ('beskrivelse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('tlf', models.IntegerField()),
                ('point', models.IntegerField()),
                ('cpr', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PointGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('minScore', models.IntegerField()),
                ('maxScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostNummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postNr', models.IntegerField()),
                ('byNavn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.TextField()),
                ('tidspunkt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uddel_Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permissions')),
                ('pointgradeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pointgrade')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport_junctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rapport')),
                ('snitchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snitch', to='api.person')),
                ('suspectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect', to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='postnummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postnummer'),
        ),
        migrations.CreateModel(
            name='Handling_Junctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handlingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.handlinger')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
