# Generated by Django 4.0 on 2023-03-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='godtaget',
            field=models.BooleanField(default=False),
        ),
    ]
