# Generated by Django 4.0 on 2023-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='brugernavn',
            field=models.CharField(default='bob', max_length=255),
        ),
    ]
