# Generated by Django 4.0 on 2023-02-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpr',
            field=models.BigIntegerField(),
        ),
    ]
