# Generated by Django 4.0 on 2023-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_brugernavn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='brugernavn',
            field=models.CharField(max_length=255),
        ),
    ]
