# Generated by Django 4.0 on 2023-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_cpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpr',
            field=models.CharField(max_length=10),
        ),
    ]
