# Generated by Django 4.0 on 2023-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=255),
        ),
    ]
