# Generated by Django 4.0 on 2023-02-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='setting',
            new_name='Settings',
        ),
    ]
