# Generated by Django 4.0 on 2023-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_setting_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='point',
            field=models.IntegerField(default=300),
        ),
    ]
